### ISSUE TITLE
Protect chat-only players (probably a command that can only be toggled once per login to prevent abusing)

### ISSUE THREAD

**Issue by NorbiPeti** [NorbiPeti/thebuttonautoflairmc#14]

**Comment by Sciguymjm** [comment]
If they are just chatting (with no actual game open) we can put them in spectator mode and give them a variety of status effects to prevent abuse (e.g. Nausea+Blindness) and have it reset on login. Also prevent them from moving, but not sure how to do that without teleporting them constantly.

**Comment by NorbiPeti** [comment]
Just do an event.setCancelled at onPlayerMove, I guess...

**Comment by NorbiPeti** [comment]
Added. I keep forgetting to reference issues from commits though.

**Comment by NorbiPeti** [comment]
Though I didn't add status effects. Do you think we need them? If the player is unable to move (and teleport) they can't really abuse it, can they?
