### ISSUE TITLE
Change greentext color from dark_green to green

### ISSUE THREAD

**Issue by Sciguymjm** [NorbiPeti/thebuttonautoflairmc#3]
https://github.com/NorbiPeti/thebuttonautoflairmc/blob/69a64aa19b4d20c2f3448936f7629bef0505abe1/TheButtonAutoFlair/src/tk/sznp/thebuttonautoflair/PlayerListener.java#L260

and

https://github.com/NorbiPeti/thebuttonautoflairmc/blob/69a64aa19b4d20c2f3448936f7629bef0505abe1/TheButtonAutoFlair/src/tk/sznp/thebuttonautoflair/PlayerListener.java#L264

**Comment by NorbiPeti** [comment]
Dark green is the equivalent of §2 which you originally provided with greentext support.
